- users:
    - "Fabricio Leotti <fabricio.leotti@gmail.com>"
<<<<<<< HEAD
    - "Chambinho Rosa <chambinho.rosa@gmail.com>"
=======
    - "Fernando La Gamba <pegaaquinomeu@world.com>"
>>>>>>> refs/remotes/origin/master
